### ISSUE TITLE
Script have problems with looping.

### ISSUE THREAD

**Issue by choodencio** [EvilFreelancer/routeros-api-php#1]
Ex. I have 5 devices, written a loop using the script.
` $config =
                          (new Config())
                              ->set('timeout', 1)
                              ->set('host', $data_tik['tikDDNS'])
                              ->set('user', $data_tik['tikUser'])
                              ->set('pass', $data_tik['tikPass']);

                      $client = new Client($config);
                      $query = new Query('/system/resource/print');
                      $response = $client->write($query)->read();`

If the connection to the second device cannot be connected
The script will stop working immediately.

Can I suggest a code?
If any device connection has a problem, report back and continue working all devices are complete.

**Comment by EvilFreelancer** [comment]
Hello! This is not a bug, script has "exceptions" inside, and on error you'll see the messages from these exceptions. Sample of code for preventing this issue:
```
use RouterOS\Exceptions\ClientException;

$client = new Client($config);
$query = new Query('/system/resource/print');
try {
  $response = $client->write($query)->read();`
} catch(ClientException $e) {
  echo $e->getMessage();
}
```

**Comment by choodencio** [comment]
Thank you.
