### ISSUE TITLE
How to handle response error properly?

### ISSUE THREAD

**Issue by fikurimax** [EvilFreelancer/routeros-api-php#103]
Is there a proper way to handle error?
as for now I handle error by using this way
```php
$response = $client->qr($query);
if (isset($response['after']['message']) {}
```
because I get this 'after' key when i get response error such as no such commands error

**Comment by EvilFreelancer** [comment]
Hi! Easiest way is handle `\Exception` or `\Throwable`.

Better way is handle `\RouterOS\Exceptions\StreamException`
https://github.com/EvilFreelancer/routeros-api-php/blob/master/src/Streams/ResourceStream.php#L70
