### ISSUE TITLE
/export does not work ROUTEROS7

### ISSUE THREAD

**Issue by Lilleri** [EvilFreelancer/routeros-api-php#106]
**Version of RouterOS**
7.11.2

**To Reproduce**
use the function export() or perform a query with the endpoint /export

**Expected behavior**
i expect to output the configuration of the mikrotik

In summary when i use export() or perform the query /export instead of receiving the configuration i receive this error
**bad command name bash (line 1 column 1)**
i saw that this error is caused by this parameter _bash -se_ when it tries to connect to the SSH to retrieve the configuration,
if i remove that i receive with success the configuration

**Comment by EvilFreelancer** [comment]
Hi, thanks for your report! Can you create a PR with your fix?

**Comment by Lilleri** [comment]
hello, i just made the PR, i cannot test if this works in the previous RouterOS versions too.

**Comment by EvilFreelancer** [comment]
@Lilleri hi! Your fix was merged, thanks!

You may try update to 1.5.1
