### ISSUE TITLE
Undefined offset: 0 in .../src/Client.php on line 244

### ISSUE THREAD

**Issue by jmross** [EvilFreelancer/routeros-api-php#11]
Hi, 

First of all, I really like this package. 

I use this package to mostly interface with queues. When creating an invalid queue (eg. queue type doesn't exist or queue name is already used), I get the notice: 

> PHP Notice:  Undefined offset: 0 in .../evilfreelancer/routeros-api-php/src/Client.php on line 244

Here's line 244: https://github.com/EvilFreelancer/routeros-api-php/blob/master/src/Client.php#L244

When creating a queue with a name that already exists, dumping `$matches` after line 242 of Client.php prints these two arrays after calling `$client->read()`:

```
array:3 [
  0 => array:1 [
    0 => "=message=failure: already have such name"
  ]
  1 => array:1 [
    0 => "message"
  ]
  2 => array:1 [
    0 => "failure: already have such name"
  ]
]
array:3 [
  0 => []
  1 => []
  2 => []
]
```
Then two notices about the undefined offset. I think it is failing on the second array where the response would be '!done'. `$match[1][0]` and `$match[2][0]` are not defined.

Should an exception be thrown instead?

I'm using Laravel and it throws an exception on notices by default.

**Comment by EvilFreelancer** [comment]
Hello @jmross and thank you for you report!
Can you please provide example of code in which you reveved this error?

**Comment by jmross** [comment]
Sure, here's a sample of the code. Basically, if I create a queue that already exists:

```
<?php
// ... 
$this->client->write([    
'/queue/simple/add',    
  '=name=' . $this->name,    
  '=queue=' . $this->upload.'/'.$this->download,    
  '=target=' . implode(',', $this->target),    
  '=comment=' . $this->comment,       
  '=disabled=' . ($this->disabled === true ? 'yes' : 'no')    
]);

$res = $this->client->read();
// notice happens here
```

**Comment by EvilFreelancer** [comment]
I've checked, your solution is fine, just need fix style of code little bit :)

**Comment by EvilFreelancer** [comment]
@jmross your updates in 0.9.1, well done :+1:
