### ISSUE TITLE
Stream timed out error

### ISSUE THREAD

**Issue by fikurimax** [EvilFreelancer/routeros-api-php#110]
I often get stream timed out error, I wonder what's the problem. As it's not always happening, but quite often lately

**Comment by EvilFreelancer** [comment]
Hi! Try to play with timeout options:

https://github.com/EvilFreelancer/routeros-api-php?tab=readme-ov-file#list-of-available-configuration-parameters

**Comment by fikurimax** [comment]
Hi @EvilFreelancer! I've tried to set the timeout from 30, 60, 120. but still get the error. Any other solutions?

**Comment by fikurimax** [comment]
Hi, sorry for reopening this issue. In my case, communication between my server and the Mikrotik device is quite frequent, but sometimes this problem occurs. So, it's not that I can't connect to the Mikrotik at all, but rather it happens occasionally.
