### ISSUE TITLE
windows Socket timeout reached

### ISSUE THREAD

**Issue by Linqh1215** [EvilFreelancer/routeros-api-php#112]
Display Socket timeout reached during Windows development process

**Comment by 1260545050** [comment]
Error message ： Unable to establish socket session，How does the solve it?

**Comment by EvilFreelancer** [comment]
Hi! Your issue is probably a duplicate of #111

**Comment by nestinho** [comment]
"Unable to establish socket session, A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."

On regard to this kind of question, i am also getting similar thing latest.

**Comment by EvilFreelancer** [comment]
Hi! This mean router is unavailable from the side where you make a library call.
