### ISSUE TITLE
Unable to establish socket session, some sort of timeout error.

### ISSUE THREAD

**Issue by nestinho** [EvilFreelancer/routeros-api-php#113]
"Unable to establish socket session, A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond." 

The package were working fine on my cpanel for couple of weeks and everything were working just fine. Now all-of-a-sudden it stops working and I stack here for like three weeks am looking for  a solution and am no way near to get one.

Kindly anyone with the help will be much appreciated. I tried to follow some suggestions in here but still seems to the perfect solution for my case.

Otherwise, the package is very very good for anyone.

**Comment by EvilFreelancer** [comment]
This mean your router is unavailable via API from the server where you use this library.

**Comment by nestinho** [comment]
Hello, thanks for replying. Issue resolved. It always happen when the
server hosting the library blocks the IP & Port of the Router.

Thanks for such an amazing library. It's a life saver.

👍

**Comment by EvilFreelancer** [comment]
That's right!

I apologize for such a long answer :)

**Comment by sp0ng3808** [comment]
> Hello, thanks for replying. Issue resolved. It always happen when the server hosting the library blocks the IP & Port of the Router. Thanks for such an amazing library. It's a life saver.

How to solving?

**Comment by EvilFreelancer** [comment]
@sp0ng3808 hi! You just need to open port on router side.

**Comment by gensart-x** [comment]
sometimes the api cannot be reached, and sometimes able.

```
evilfreelancer\routeros-api-php\src\SocketTrait.php line 58: Unable to establish socket session, A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
```

had no idea why. I've checked with different app with same method, it connected well.
