### ISSUE TITLE
Random Stream timed out

### ISSUE THREAD

**Issue by juanfcomartin** [EvilFreelancer/routeros-api-php#114]
**Version of RouterOS**
RouterOS 7.8 running on CCR2116-12G-4S+

**To Reproduce**
```
$client = new Client([
            'host' => $config['host'],
            'user' => $config['user'],
            'pass' => $config['password'],
            'port' => intval($config['port']),
        ]);
$query = new Query('/ip/firewall/filter/print');
$response = $client->query($query)->read();
```
**Expected behavior**
From time to time, I get the "Stream timed out" error when calling $client->query($query)->read(). It really isn't a timeout issue as I'm sniffing the traffic and I can see that the communication is taking place and the client is receiving the request from RouterOS but for some reason, an exception is launched inside ResourceStream:
```
if(socket_get_status($this->stream)['timed_out']){
            throw new StreamException('Stream timed out');
}
```

**Comment by EvilFreelancer** [comment]
Hi! I guess you increased `socket_timeout` option from default `30` seconds and solved your issue.

**Comment by bangyadiii** [comment]
I have the same problem. With the same code, sometimes it works, sometimes it doesn't.

My configuration looks like this:

```<?php

return [
...
    'attempts'        => 5,   // Count of attempts to establish TCP session
    'delay'           => 1,    // Delay between attempts in seconds
    'timeout'         => 65,   // Max timeout for instantiating connection with RouterOS
    'socket_timeout'  => 60,   // Max timeout for read from RouterOS
    'socket_blocking' => false, // Set blocking mode on a socket stream
..
]
```
My RouterOS version is 7.14.1 (CHR Mikrotik)

FYI, I moved to [this ](https://github.com/wasiswsn/RouterOS-API-for-monitoring-mikrotik/blob/main/RouterosAPI.php). It worked for me. No more random stream error
