### ISSUE TITLE
remove active hotspot user problem

### ISSUE THREAD

**Issue by alfanariamustofa** [EvilFreelancer/routeros-api-php#118]
my hotspot user active in multiple device 
when i remove one by .id like this code:

```
$query = new Query('/ip/hotspot/active/remove');
$query->equal('.id', '*C0A80A08');
$result = $client->query($query)->read(false);
```
all device active for the same user was removed too

when check log showing this message 
`USER (xxx.xxx.xxx.xxx): logged out: admin reset`

**Comment by EvilFreelancer** [comment]
Hi! It sounds like an issue with RouterOS (not with API library), did you asked Miktorik's [support](https://mikrotik.com/support) or on [forum](https://forum.mikrotik.com/)?

**Comment by alfanariamustofa** [comment]
> Hi! It sounds like an issue with RouterOS (not with API library), did you asked Miktorik's [support](https://mikrotik.com/support) or on [forum](https://forum.mikrotik.com/), maybe on [reddit](https://www.reddit.com/r/mikrotik/)?

i build with kotlin language for android app with NabilNoN/Mikrotik-Android library running well
