### ISSUE TITLE
does not support mikrotik chr v7, but works on local mikrotik v6 and v7

### ISSUE THREAD

**Issue by KodekaTeamOfficial** [EvilFreelancer/routeros-api-php#123]
![image](https://github.com/user-attachments/assets/f7af7046-4cff-49d6-a41f-3ffc5f213928)

hello, I'm a new user using your project. after I switched from the RouterOs API which required using RouterOs min. v7++

I see that your project is the result of the development of 'BenMenking'. 

And I want to ask, can your project be used with an HTTP/HTTPS connection like I use the official RouterOs API?

Previously I had tried connecting it to the Mikrotik Chr V7, but experienced an error. And I also tried connecting it to the local mikrotik v7 too, and it worked.

because coincidentally I also use CHR v7 which I associate with a reverse mikrotik (cloudflare) so that I can have a subdomain for each chr mikrotik .

If you like, can you make it work like me using the official RouterOs API?

**Comment by KodekaTeamOfficial** [comment]
![image](https://github.com/user-attachments/assets/27bf28bf-6ad0-44ef-88d1-f8732723ace0)

you know, this seems like a bug.
so, when I want to update ip/pool/set, in the first code I rely on the same '.id', 

but in the second code, when I entered queryData in the form of the name of the pool, it turned out that the data in my mikrotik was successfully updated. even though '.id' and 'name' are not the same/equivalent

I also had a bit of difficulty adjusting what was written in the tutorial on 'README', I think it needs an update to make it easier to understand

**Comment by EvilFreelancer** [comment]
Hello! Look at #56
