### ISSUE TITLE
remove ip-binding not work

### ISSUE THREAD

**Issue by zhongkon** [EvilFreelancer/routeros-api-php#16]
don't work 

$user = $client->query('/ip/hotspot/ip-binding/print', ['mac-address', '00:00:00:00:00:A9'])->read();
if (isset($user[0]['.id'])) {
    $userId = $user[0]['.id'];
    $removeUser = $client->query('/ip/hotspot/ip-binding/remove', ['.id', $userId])->read();
    print_r($removeUser);
}

Result:
Array ( )
Don't remove

**Comment by EvilFreelancer** [comment]
Hello! Thanks for report, which version of RouterOS you use? And how to add some IP/MAC-address to hotspot? Just login to Wi-Fi network?

**Comment by zhongkon** [comment]
which version of RouterOS you use
my RouterOS is 6.45.6

how to add some IP/MAC-address to hotspot?

$out = $client->write(['/ip/hotspot/ip-binding/add', '=mac-address=00:00:00:00:40:29','=type=bypassed','=comment=testcomment'])->read();
print_r($out);

Thanks for support

**Comment by EvilFreelancer** [comment]
Hello @zhongkon ! I found the reason of your issue, it was an incorrect word inside '/ip/hotspot/ip-binding/remove' query, [here](https://github.com/EvilFreelancer/routeros-api-php/blob/master/examples/hotspot.php) is the fully functional example based on your sample.

For writing get queries you should use `where()` method of Query class, but for set queries (like update or create) you should use `equal()` method of Query.

The `equal()` method is already available in 1.1 version of this library, please update and if everything is fine then please close this issue. Thanks!

**Comment by zhongkon** [comment]
great job

Thanks for support
