### ISSUE TITLE
Bug with `/ppp/active/print`

### ISSUE THREAD

**Issue by EvilFreelancer** [EvilFreelancer/routeros-api-php#17]
**Version of RouterOS**
Need to know version

**To Reproduce**
```
// Initiate client with config object
$client = new Client([
'host' => '138.185.236.230',
'user' => 'api_mk',
'pass' => 'senha_aqui',
'timeout' => 5,
'attempts' => 1
]);

//lembrar de verificar se a variavel $cliente foi gerada e se não gerar exception
print_r($client);
//the connection it runs smoothly	

///the problem is here
// Send query and read response from RouterOS
$response = $client->wr('/ppp/active/print',false);
var_dump($response);

exit;
```

**Expected behavior**
From @gamadoleo:
> but as I said this looping problem when executing want only occurs if l2m3u is set wrong, for example l2m3u = 1500
> But the question is as follows, even with the wrong m3u would not be able to download the data or display an exception, because the situation is as follows when I get no error I get lost without knowing which one is really the error

**Comment by EvilFreelancer** [comment]
@gamadoleo what version of RouterOS you have?

**Comment by gamadoleo** [comment]
version Mikrotik RouterOS 6.42.12

**Comment by EvilFreelancer** [comment]
I've tried several times to reproduce your problem, but it have never succeeded, I close the task, sorry
