### ISSUE TITLE
use for monitor traffic

### ISSUE THREAD

**Issue by ones006** [EvilFreelancer/routeros-api-php#19]
hi EvilFreelancer, 
I hope you can give me instructions, how to run the command "/interface/monitor-traffic interface=ether1 once", with this library/package

thanks

**Comment by EvilFreelancer** [comment]
Hello @ones006 !

It's a good question, here is the working sample of code:
```
// Build monitoring query
$query =
    (new Query('/interface/monitor-traffic'))
        ->equal('interface', 'ether1')
        ->equal('once');

// Ask for monitoring details
$out = $client->query($query)->read();
print_r($out);
```
Full sample will be [here](https://github.com/EvilFreelancer/routeros-api-php/blob/master/examples/monitoring.php)

**Comment by ones006** [comment]
@EvilFreelancer Thank you very much. this is very helpful   👍🏽

**Comment by Mrjavaci** [comment]
Can I execute this query asynchronously?

**Comment by EvilFreelancer** [comment]
As I know there is some limitations of API server of RouterOS, especially of output buffer, but I've never tested async mode of php stream, probably it will work.

**Comment by Mrjavaci** [comment]
Thank you bro!
