### ISSUE TITLE
How to get full source from system script print?

### ISSUE THREAD

**Issue by ones006** [EvilFreelancer/routeros-api-php#20]
i'm try this:

$scriptQue = (new Query('/system/script/print'));
$scriptReq = $lynx->write($scriptQue);
$script = $lynx->read();

and result:
Array
(
    [0] => Array
        (
            [.id] => *3
            [.nextid] => *5
            [name] => script1
            [owner] => admin
            [policy] => ftp,reboot,read,write,policy,test,winbox,password,sniff,sensitive,api
            [last-started] => oct/19/2019 09:36:44
            [run-count] => 8992
            [source] => :local monitor [/interface monitor-traffic ether2 as-value once]
            [invalid] => false
        )
)

why thi _[source] => :local monitor [/interface monitor-traffic ether2 as-value once]_ can't get full source ? and last, you have solution for this case ? 

thanks.

**Comment by EvilFreelancer** [comment]
Hello! I've not used scripts of ROS previously, can you provide sample of how to create it and how to use it?

**Comment by ones006** [comment]
hi @EvilFreelancer 
thank you for responding to my question. actually I'm not really sure either. at the moment I am just trying to experiment for my small project. I plan to write a script like this:

$config = (new Config())
			->set('timeout',1)
			->set('host', '192.168.88.1')
			->set('user', 'admin')
			->set('pass', '');
		
$client = new Client($config);

$create = $client->write(['/system/script/add', "=name=test_by_system2",'=source=:local monitor [/interface monitor-traffic ether2 as-value once] \r\n
:local speedRX ($monitor->"rx-bits-per-second")\r\n
:local speedTX ($monitor->"tx-bits-per-second")\r\n
/tool fetch mode=http url=("http://192.168.254.72/micro-nms/storebw/1/$speedTX/$speedRX")  keep-result=no'])->read();	

and then i create scheduler by this way:

$config = (new Config())
    ->set('timeout',1)
    ->set('host', $params[1])
    ->set('user', $params[2])
    ->set('pass', $params[3]);
  
  $client = new Client($config);
  $query = (new Query('/system/scheduler/add'))
    ->equal('name','monitoring22')
    ->equal('on-event','monitoring')
    ->equal('interval','1s')
    ->equal('start-time','startup');
    $response = $client->write($query)->read();

until here all went well, the problem arises when I want to display the script that I wrote before. in the following way

$config = (new Config())
    ->set('timeout',1)
    ->set('host', $params[1])
    ->set('user', $params[2])
    ->set('pass', $params[3]);
  
  $client = new Client($config);
  $scriptQue = (new Query('/system/script/print'));
  $scriptReq = $client->write($scriptQue);
  $script = $client->read();

and this method works, but not the results can not display the full script, this method only displays the first 1 line of code. I do not understand what's wrong.
previously I apologize if the English I use is not good

**Comment by EvilFreelancer** [comment]
Okay, ill check it from my side.
Btw, you can try to use `->read(true)` instead `->read()` method, it will return unparsed results.
And do not worry about English, I'm also is not a native speaker :)

**Comment by EvilFreelancer** [comment]
Hello! I've checked your issue (sorry for so long response, very hard to find spare time).

If I understand correctly, you have some issue with creating system scripts, your solution show me shorted version of line which you want to call via scheduller, you need slightly change line (add line concatenation) and everything will work.

I've created [small example](https://github.com/EvilFreelancer/routeros-api-php/blob/master/examples/system_script.php) by your code, which should show what everything is almost okay, but need to add small fix.

![Screenshot_20191024_143005](https://user-images.githubusercontent.com/9089568/67481537-d4488700-f66a-11e9-8deb-e3b52e02b975.jpg)
![Screenshot_20191024_142957](https://user-images.githubusercontent.com/9089568/67481538-d4e11d80-f66a-11e9-8062-d2e1765acffe.jpg)

**Comment by ones006** [comment]
hi @EvilFreelancer, thank you for the solution. I really appreciate the effort and time you spent helping me.
