### ISSUE TITLE
Unable to establish socket session

### ISSUE THREAD

**Issue by nkuldip** [EvilFreelancer/routeros-api-php#21]
Getting error on live server
Fatal error: Uncaught RouterOS\Exceptions\ClientException: Unable to establish socket session, Connection timed out RouterOS\Client->openSocket() #1 /home3/apptific/public_html/b2b_mikrotik/vendor/evilfreelancer/routeros-api-php/src/Client.php(60): RouterOS\Client->connect() #2 /home3/apptific/public_html/b2b_mikrotik/test.php(16): RouterOS\Client->__construct(Object(RouterOS\Config)) #3 {main} thrown in /home3/apptific/public_html/b2b_mikrotik/vendor/evilfreelancer/routeros-api-php/src/SocketTrait.php on line 63

**Comment by EvilFreelancer** [comment]
Hello! It seems like your Mikrotik device is unavailable for api client. You checked ability to connect via for example telnet of ssh?

**Comment by nkuldip** [comment]
On test server it's working fine http://137.74.253.59/b2b_mikrotik/test.php

Same code set on product it's not working https://srpvolvoparts.com/b2b_mikrotik/test.php

**Comment by EvilFreelancer** [comment]
And you checked availability of RouterOS from production server via command line?

**Comment by nkuldip** [comment]
how can i check it ?

**Comment by EvilFreelancer** [comment]
It should be easy, you just need login to production server and check access to API port of your RouterOS, it should be 8728 or 8729 (in ssl mode) if you not changed it via config.

`nmap` might be useful for you:
```
~$ nmap -p 8728 192.168.1.1
Starting Nmap 7.80 ( https://nmap.org ) at 2019-10-21 13:26 MSK
Nmap scan report for router.lan (192.168.1.1)
Host is up (0.00039s latency).

PORT     STATE SERVICE
8728/tcp open  unknown

Nmap done: 1 IP address (1 host up) scanned in 0.04 seconds
```

If you don't have nmap on server then just try to start from `ping` and `ssh`, but for the fist you need login to your production server via `ssh`.

If you are a Windows user, then most likely you will be more comfortable using the PuTTY program instead CLI ssh client.

https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html

**Comment by EvilFreelancer** [comment]
@nkuldip hi! Did it work for you?

**Comment by tahsin352** [comment]
I am also getting socket timeout.

```
nmap -p 8441 103.111.15.30

Starting Nmap 7.60 ( https://nmap.org ) at 2019-10-26 19:03 +06
Nmap scan report for 103.111.15.30
Host is up (0.056s latency).

PORT     STATE SERVICE
8441/tcp open  unknown

Nmap done: 1 IP address (1 host up) scanned in 2.35 seconds

```

**Comment by nkuldip** [comment]
> @nkuldip hi! Did it work for you?

yes working

**Comment by lgabrielc** [comment]
Hi! Hello, I also have the same error and when using NMAP I get this as a result:
nmap -p 8728 192.168.1.1
Starting Nmap 7.92 ( https://nmap.org ) at 2022-08-19 00:29 UTC
Note: Host seems down. If it is really up, but blocking our ping probes, try -Pn
Nmap done: 1 IP address (0 hosts up) scanned in 3.16 seconds.
Could you help me please ?

**Comment by toxicking-techguru** [comment]
i am getting this error on cpanel  but works on localhost 


RouterOS\Exceptions\ConnectException
Unable to establish socket session, Connection refused
