### ISSUE TITLE
is there a way to use monitor command for a duration.

### ISSUE THREAD

**Issue by justin-sl** [EvilFreelancer/routeros-api-php#22]
Is there a way with this to use the monitor command for a time period then return the results

Eg command line command
/interface ethernet monitor ether4 duration=1

Would run for 1 second the output the last result.

**Comment by EvilFreelancer** [comment]
Hello! Sorry for long response, I just forgot about your issue. [Here](https://github.com/EvilFreelancer/routeros-api-php/blob/master/examples/monitoring.php) is the example
```
$query =
    (new Query('/interface/monitor-traffic'))
        ->equal('interface', 'ether1')
        ->equal('once');
```
