### ISSUE TITLE
how to send write qury

### ISSUE THREAD

**Issue by xbipin** [EvilFreelancer/routeros-api-php#23]
i need to send the below using this library but doesnt seem to work, if i type it from winbox terminal it works:
radius remove [find]

i tried using
$out = $client->write('/radius/remove [find]')->read();

**Comment by EvilFreelancer** [comment]
Hello!

You may have noticed that the `->write()` method is marked as deprecated, so I recommend to use `->query()` analog, which has almost same logic.

In "How to use" block of $this project readme you may find information about writing "create/update/delete" queries:
```php
// If you need create query for "create/update/delete" operations
$query = new Query('/ip/hotspot/ip-binding/add');
$query->equal('mac-address', '00:00:00:00:40:29');
$query->equal('type', 'bypassed');
$query->equal('comment', 'testcomment');
```

For sending request better to use `->query()` method of client:
```php
$response = $client->query($query)->read();
```

An finally, code for your case:
```php
$query = new Query('/radius/remove');
$query->equal('[find]');

$response = $client->query($query)->read();
```

Queries via ROS API and ordinary commands via ROS CLI has slightly different syntax, more details about this you may find here https://wiki.mikrotik.com/wiki/Manual:API#API_words

I hope this helps you in solving your problem :)
