### ISSUE TITLE
cant display full script if the script contain new line

### ISSUE THREAD

**Issue by skolastikarhea** [EvilFreelancer/routeros-api-php#24]
hi,
i got issue like this https://github.com/EvilFreelancer/routeros-api-php/issues/20, but for me is not solved.

fyi, mikrotik version 6.44.6 (long term)

i create script manualy on mikrotik, like this
![image](https://user-images.githubusercontent.com/38370219/71318236-a93eb000-24c0-11ea-926b-54e71b17a665.png)

then i create php file with this data : 

```
<?php
require_once 'vendor/autoload.php';
error_reporting(E_ALL);
use RouterOS\Client;
use RouterOS\Query;
$client = new Client([
    'timeout' => 1,
    'host'    => 'my host',
    'user'    => 'my user',
    'pass'    => 'my pass',
    'port'    => my port,
]);

$query = (new Query('/system/script/print'))
            ->where('name','test_script');
$response = $client->query($query)->read();
print_r($response);

```

and this is the result : 

![image](https://user-images.githubusercontent.com/38370219/71318307-c031d200-24c1-11ea-8b4b-8f9c2b02b06f.png)

the results can not display the full script, this method only display the first 1 line of code.

can i get full script (3 lines code) without changing my source script?

previously I apologize if the English I use is not good

**Comment by EvilFreelancer** [comment]
Hello! Sorry for long response, all problems with scripts are very individual, have you checked the result returned by the RouterOS through the command line? If results is different, then issue in library, if same then in script which you created.

**Comment by EvilFreelancer** [comment]
Hello, any updates?
