### ISSUE TITLE
Class 'RouterOS\Laravel\ClientServiceProvide' not found

### ISSUE THREAD

**Issue by bkd27** [EvilFreelancer/routeros-api-php#25]
**Version of RouterOS**
Ubuntu 18.4

**To Reproduce**
When we use latest version 1.2.0 then this error occurred in laravel installation 'Class 'RouterOS\Laravel\ClientServiceProvide' not found'

**Expected behavior**
Older version 1.1.1 is working fine with laravel but the new version is throwing error 'Class 'RouterOS\Laravel\ClientServiceProvide' not found'

**Comment by EvilFreelancer** [comment]
Hello! Thanks for report, was a typo in composer.json file and i've just fixed it. Please update to 1.2.1

**Comment by EvilFreelancer** [comment]
And by the way, from 1.2.0 you may use this library as laravel facade, it's simple `\RouterOS::getClient()` will return to you object of this library. Details is [here](https://github.com/EvilFreelancer/routeros-api-php#laravel-framework-support)

**Comment by bkd27** [comment]
Thank you for quick resolve.

**Comment by EvilFreelancer** [comment]
Sorry for typo :)
