### ISSUE TITLE
undefined character (Spanish language)

### ISSUE THREAD

**Issue by avelk101209** [EvilFreelancer/routeros-api-php#28]
Hello, I am creating a simple interface for an ISP in the country of Colombia in which the Spanish language is spoken and the api does not detect the character (ñ - Ñ)

Can you solve this problem?

I appreciate your response

**Comment by EvilFreelancer** [comment]
Hello! RouterOS does not support national languages, only English (and API of RouterOS too).
You can try to reproduce your bug via web, for example add the comment to any element of your system, then save and reload the page, you will see unreadable characters.

**Comment by avelk101209** [comment]
ok, muchas gracias
