### ISSUE TITLE
A problem in queries with operators > and <.

### ISSUE THREAD

**Issue by sashkov** [EvilFreelancer/routeros-api-php#30]
Hello!
I have got a problem in working with queries to firewall connections which have operators > and <.
I use function qr on client with all three params.
```
$endpoint = '/ip/firewall/connection/print';
$where = [['protocol','tcp'],['reply-src-address','>','172.20.41.183:3388'],['reply-src-address','<','172.20.41.188:3390']];
$operations='&&';
$data = $client->qr($endpoint,$where,$operations);
```
I have analyzed my problem with the list of where filters.
I've noticed, that the code of Query.php build string with operators like:
```
?protocol=tcp
>?reply-src-address=172.20.41.183:3388
<?reply-src-address=172.20.41.188:3390
```
But according to the Wiki the lines should be:
```
?protocol=tcp
?>reply-src-address=172.20.41.183:3388
?>reply-src-address=172.20.41.188:3390
```

More, if I just use where filter ['protocol','=','tcp'] then I receive message from my router:
message=unknown parameter
The string was sent:
=?protocol=tcp
But should be either "?=protocol=tcp" or "?protocol=tcp"

Maybe there is another function in your library to use queries with certain operators?

**Comment by EvilFreelancer** [comment]
Hello! Thanks for your report. Which version of library you use?
I've asked, because in 1.1 was added ->equal() method to Query class, especial for things with `=` symbol.
`>` and `<` symbols i'll check soon, probably here is the bug.

**Comment by sashkov** [comment]
I use composer, as I see it has installed the version 1.1.1 (my project use php 7.1.33, laravel 5.8). Here:
```
>composer show evilfreelancer/routeros-api-php
name     : evilfreelancer/routeros-api-php
descrip. : Modern Mikrotik RouterOS API PHP7 client for your applications
keywords : PSR-4, mikrotik, routeros, socket-client
versions : * 1.1.1
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
source   : [git] https://github.com/EvilFreelancer/routeros-api-php.git 31736bc231ac399450d086363999f363488d71f0
dist     : [zip] https://api.github.com/repos/EvilFreelancer/routeros-api-php/zipball/31736bc231ac399450d086363999f363488d71f0 31736bc231ac399450d086363999f363488d71f0
path     : C:\php\eclipse-workspace\laravel\vendor\evilfreelancer\routeros-api-php
names    : evilfreelancer/routeros-api-php

autoload
psr-4
RouterOS\ => ./src/

requires
ext-sockets *
php ^7.1

requires (dev)
phpunit/phpunit ^7.0
```
yes, I use ->equal() for `=`, thank you, very usefull.
OK, I didn't know that I use old version of your library.
I will test my test environment with last version.
Thank you for answer and advice to check version (because I thought composer installed last version).

**Comment by sashkov** [comment]
I've updated the library to 1.2.1 and still getting such situation.
I debugged in Query.php function `where` with all three params `(key,value,operator)` and noticed next.
In line 90 ? concats with key (`'?' . $key`) and after that there is a call a private function `world`.
In fnc `world `in line 132 operator concats with key (`$operator . $key`).
Here the key is `?reply-src-address` and the operator is `>`.
After concat key is  `>?reply-src-address`, but should be `?>reply-src-address`.
What do you think about it?
Sorry if I'm wrong.

**Comment by EvilFreelancer** [comment]
Hello! I've checked this issue, and can suggest solution, you may try to use '?key' as key name, instead ['key', '?'] combination. Soon i've add another method (eg. "->more()") for this.

**Comment by EvilFreelancer** [comment]
And sorry for long response, I was on vacation and after i've back was a hard week of work :)

**Comment by sashkov** [comment]
Hello! Thank you for this suggestion. 
Right, it would be completely comportable with methods like "->more()". 
It is your project, so it is obvious that you take your time for your work as much as you need :)
My production project is working with your current library, so I'll close this question.

**Comment by EvilFreelancer** [comment]
Not only mine, many made their contribution, I've just started it :)

If you have the opportunity, you also can implement the necessary functionality, this is done very simply, just see how the where and equal methods work, then suggest the "pull request". It will speed up the implementation process.
