### ISSUE TITLE
Attempting to set Interface to disable

### ISSUE THREAD

**Issue by zulandar** [EvilFreelancer/routeros-api-php#31]
So I am attempting to set an interface to disable via query. Here is what I have but doesn't seem to be working.

```
$query = new Query('/interface/set');
$query->where('name', 'ether5');
$query->equal('disabled', 'yes');

$response = $client->query($query)->read();
```

The response is null and no changes on the router. I can do prints, and other queries without any issues just haven't gotten the set to work

**Comment by EvilFreelancer** [comment]
Hello! Try to use something like this:
```
$query = new Query('/interface/set');
$query->equal('name', 'ether5');
$query->equal('disabled', 'yes');

$response = $client->query($query)->read();
```
Usually search queries work with "?" and requests for configuration changes with "=".

**Comment by zulandar** [comment]
@EvilFreelancer moving to equal worked. I did have to change from `'name'` to `'.id'` within the first equal.
