### ISSUE TITLE
reset-counters command

### ISSUE THREAD

**Issue by yienzhu** [EvilFreelancer/routeros-api-php#37]
Hi, do you support reset-counters operation?

Thanks

**Comment by matracine** [comment]
Hello @yienzhu,
I think the question is "Does mikrotik API supports reset counters operation ?" :smiley: 

Yes : Send a query "ip/firewall/filter/reset-counters-all" for exemple.

You can check the api commands with the Router OS shell, they have the same structure and logic.
Get a shell on a router and use tabulation key to see all the possibles combinations.
For exemple : **ip firewall filter &lt;tab&gt;** will show you the reset-counters-all and others possibilities.
Just replace spaces from the shell with slashes in the api call.
Regards,
