### ISSUE TITLE
Changing parameter value with set command

### ISSUE THREAD

**Issue by sazalahsan** [EvilFreelancer/routeros-api-php#38]
Hi, I have been trying to change parameter value (e.g. change ppp secret password) but its returning empty array. I have tried differnt combination with equal, add etc. Nothing works. Here is an example how I have been trying:

```
$query = new Query('/ppp/secret/set');
$query->where('numbers', 1);
$query->equal('password', 'test');
```

**Comment by sazalahsan** [comment]
Solved by going through closed issues. Thanks for this really nice project.

Solution:

```
$query = new Query('/ppp/secret/set');
$query->equal('.id', 1);
$query->equal('password', 'test');
```

**Comment by EvilFreelancer** [comment]
Hello! Was glad to... kinda help :) i definitely need to update documentation and add block about "equal" method.
