### ISSUE TITLE
Query PPP Set

### ISSUE THREAD

**Issue by adhityaranggap** [EvilFreelancer/routeros-api-php#43]
Hi,
I would like change profile PPP with API but I have trouble the script didn't run. This is my code : 
   ```
     // Create "where" Query object for RouterOS
        $query =
            (new Query('/ppp/secret/set/name/profile=Block'));


        // Send query and read response from RouterOS

        $response = $client->query($query)->read();
        return response()->json($response);     
```    

Could you please share how to edit or set PPP Secret?

Thank you

**Comment by EvilFreelancer** [comment]
Hello! For update/remove/create need to use [equal](https://github.com/EvilFreelancer/routeros-api-php#how-to-updateremovecreate-something-via-api) method of Query class.

Plus seems you need update your query, `set` is parameter of `/ppp secret` endpoint, so in library need to use `/ppp/secret/set` and all other parameters need pass via equal method.

Details in [this article](https://mum.mikrotik.com//presentations/NZ15/perkins.pdf) on 8 page

Small example which can solve your issue:

```php
// Get list of all available profiles with name Block
$query = new Query('/ppp/secret/print');
$query->where('name', 'Block');
$secrets = $client->query($query)->read();

// Parse secrets and set password
foreach ($secrets as $secret) {

    // Change password
    $query = (new Query('/ppp/secret/set'))
        ->equal('.id', $secret['.id'])
        ->equal('password', 'pa$$word');

    // Update query ordinary have no return
    $client->query($query)->read();
}
```
Full example [here](https://github.com/EvilFreelancer/routeros-api-php/blob/master/examples/ppp_secret_password.php).

**Comment by adhityaranggap** [comment]
Thank you! It's worked!
