### ISSUE TITLE
Can't Catch Exception When Connection Couldn't Established

### ISSUE THREAD

**Issue by 14mdzk** [EvilFreelancer/routeros-api-php#45]
Hi, I'm just started using this projects.
I already could connecting my application (local) into the router intended but when I didn't set the configuration for `\RouterOS\Client` properly or my pc didn't have any connection to router it always throw

`
"message": "Unable to establish socket session, No connection could be made because the target machine actively refused it.",
"exception": "RouterOS\\Exceptions\\ClientException"`

even though I already wrap it inside Try and Catch like this:

```
public function connectToRouterByIp($ip)
    {
        $router = $this->router->whereIpAddress($ip);
        try {
            $this->client = new \RouterOS\Client([
                'host' => $router->ip_address,
                'user' => $router->username,
                'pass' => $router->password,
                'port' => $router->port ?? 8728
            ]);
            $this->message['message'] = 'Can\'t establish connection';
        } catch (\Exception $e) {
            $this->message['message'] = 'Can\'t establish connection';
            return $this;
        }

        return $this;
    }
```

Did I do something that must not be done ? 
Anyway, thanks for this amazing projects!

**Comment by EvilFreelancer** [comment]
Hello @14mdzk thanks for report!

Probably your router is not available via API, did you checked [known issues](https://github.com/EvilFreelancer/routeros-api-php#unable-to-establish-socket-session-operation-timed-out) block of readme?

**Comment by EvilFreelancer** [comment]
Plus router should be preconfigured before you start using API, al least should be set password of admin user, without password library can't connect to router, small example how make it in automatical way is [here](https://github.com/EvilFreelancer/routeros-api-php/blob/master/preconf.tcl).

**Comment by EvilFreelancer** [comment]
`tests/ClientTest.php` - contains samples about how to connect and how to catch wrong connection code, in your case need to use ClientException

**Comment by 14mdzk** [comment]
> Hello @14mdzk thanks for report!
> 
> Probably your router is not available via API, did you checked [known issues](https://github.com/EvilFreelancer/routeros-api-php#unable-to-establish-socket-session-operation-timed-out) block of readme?

Yes, I've already configured my router and already connected to the router.
Thanks for quick reply :)

**Comment by 14mdzk** [comment]
> `tests/ClientTest.php` - contains samples about how to connect and how to catch wrong connection code, in your case need to use `RouterOS\Exceptions\ClientException` for catching only client's errors, if issue with config need to use `RouterOS\Exceptions\ConfigException`.
> 
> List of all available exceptions is [here](https://github.com/EvilFreelancer/routeros-api-php/tree/master/src/Exceptions).

Nah, I also tried to catch the exception when router is not connected or there's wrong configuration. What I want is to customize the message catched from them `RouterOS\Exceptions\ClientException` or `RouterOS\Exceptions\ConfigException`  to my own message instead.

**Comment by 14mdzk** [comment]
Solved!
I have already found out why I can't override the exception and it's totally my mistake for not noticing how I handled the Errors.

Thanks for helping, 👍
