### ISSUE TITLE
More detail exceptions

### ISSUE THREAD

**Issue by majsterkoo** [EvilFreelancer/routeros-api-php#49]
Hi,
ClientException is used for 
 - unable to connect...
 - invalid user name or password
 - From 1 to 3 parameters of "where" condition is allowed

In my script, when unable to connect to device, then I try ssh connection instead (sometimes api port is disabled). In this exceptions case, there is not a good way (?), how I can recognize between "unable to connect" versus "invalid user name").
Can you add more exceptions or other improvement...  or did I miss something?

Thanks.

**Comment by EvilFreelancer** [comment]
Hello! Yeah, need to implement this as you explained, I'll try to make it on vocation ;)

**Comment by majsterkoo** [comment]
Hi, because I need this "feature", I implemented it in fork project. If you want, I can create PR.. https://github.com/majsterkoo/routeros-api-php

**Comment by EvilFreelancer** [comment]
Hello, yes, please create a PR, it will be nice.

**Comment by EvilFreelancer** [comment]
By the way, please do not forget to write unit tests, which will check these exceptions. More details about testing in readme.

**Comment by EvilFreelancer** [comment]
Your fixes already in 1.3.3, well done.

**Comment by majsterkoo** [comment]
Ok, thanks :)
