### ISSUE TITLE
[FR] Add support for PHP 8

### ISSUE THREAD

**Issue by kiler129** [EvilFreelancer/routeros-api-php#52]
**Version of RouterOS**
N/A

**To Reproduce**
Package is not installable under PHP 8.

**Expected behavior**
Package should be compatible with the current stable release, i.e. 8

I did some work in https://github.com/EvilFreelancer/routeros-api-php/pull/51 to see how badly Travis explodes.

**Comment by EvilFreelancer** [comment]
Hello! Yeah, it's a good point, thanks, I'll check.

**Comment by EvilFreelancer** [comment]
Hello! I've checked your PR and seems it's not work on PHP 8 even after fixing dependencies.

I found the way how to fix it and released 1.4.0, so you may use it already :)

**Comment by EvilFreelancer** [comment]
Please check and share the results :)

**Comment by kiler129** [comment]
I had some time to throughly test it in https://github.com/kiler129/mikrotik-auto-wireguard/ and it works like a charm. Thanks :)

**Comment by EvilFreelancer** [comment]
Thank you for your feedback, I'm glad that the library works without issues.
