### ISSUE TITLE
No such command when activating profile

### ISSUE THREAD

**Issue by hashweather** [EvilFreelancer/routeros-api-php#53]
I am trying to activate a Profile for my registered user using the below function

  ```
public function activateProfile($username)
    {
        $activateProfileQuery = new Query(
            "/tool/user-manager/user/create-and-activate-profile/" . $username,
            [
                '=customer=admin',
                '=profile=24hrs Unlimited'
            ]
        );
        $response = $this->query($activateProfileQuery)->read(false);
        print("Activating Profile...");
        print_r($response);
    }
```

But I keep getting the error message below

`Activating Profile...Array ( [0] => !trap [1] => =message=no such command [2] => !done )`

Please help. 

Thank you for this amazing library.

**Comment by EvilFreelancer** [comment]
@hashweather hello!

It looks like you have no installed package with "User Manager" tool.

Try this manual:
https://help.mikrotik.com/docs/display/ROS/User+management

> MikroTik User Manager can be downloaded from the MikroTik web site [download](https://www.mikrotik.com/download) section. In there find the system and software version that you need this package for and download **Extra packages** archive for it. In this archive, you will find the User Manager package. To install the package simply upload it on the device and reboot the unit.

PS. Sorry for long response.

**Comment by hashweather** [comment]
Ok. Though I already have user manager. I just discovered that I needed to add a `=numbers= ` attribute before it would work.

The moment I added the` =numbers= `attribute, profile activation worked.

Thanks for this amazing library and for your time.
