### ISSUE TITLE
Unable to establish socket connection "no route to host"

### ISSUE THREAD

**Issue by hashweather** [EvilFreelancer/routeros-api-php#56]
Hello, thanks for this amazing library.

Everything worked really well until I deployed the php script to an online server and I then I started getting the error message
`Unable to establish socket connection "no route to host"` whenever I try to openSocket.

Do you have any idea on how to resolve this?

Thanks.

**Comment by EvilFreelancer** [comment]
Hey! Typically, this error occurs if the library cannot connect to the router. For example, because the router is protected by a firewall or simply turned off.

Try to use the ping utility from the server on which the library is running, most likely the ping will show that the router is not responding to requests.

**Comment by hashweather** [comment]
Hello, thanks for your response. I have tried the ping utility and unfortunately the server is responding but not responding when trying to connect via the api. Honestly, this is surprisingly weird because initially it worked when I connected for the first time. I wonder what changed? I am still getting `Unable to establish socket session, No route to host` as an error message till this time.

Any more suggestions on how to resolve this would be highly appreciated.

**Comment by EvilFreelancer** [comment]
Okay, if server available but not accessible then issue probably in API port.

Here the sample of which trigger this error:
https://github.com/EvilFreelancer/routeros-api-php/blob/master/src/SocketTrait.php#L45-L61

As you can see here can be enabled SSL mode and need to pass host and port.

Can you check via `nmap $host -p 8728,8729` status of these API ports?

**Comment by matracine** [comment]
Hello,
The 'No route to host' message is triggered by the IP stack of your client when a router on the path has no way to join the target or refuse "politely". 
If you can ping the Mikrotik's IP, it's pretty sure that a firewall blocks the port communication and send a ICMP message 'port-unreachable' that is traducted by you system with "No route to host".
See : https://superuser.com/questions/1224383/why-am-i-getting-no-route-to-host for example.
It's a network problem, not a lib issue.
First, check on your Mikrotik that no firewall flter input rule block the communication.
Then, has Paul suggest, do a port reachability test with nmap.

**Comment by VelaJafet** [comment]
I had the same issue, but I just used the ssh_port:

$cliente = new Client([
            'host' => $access->DireccionIP,
            'user' => $access->Usuario,
            'pass' => $access->Password,
            'port' => $access->Puerto,
            'ssh_port' => 8722
        ]);

**Comment by EvilFreelancer** [comment]
@VelaJafet hello! This library can work only with API port, so it should be available from server where the library is installed and used.
