### ISSUE TITLE
Running Script

### ISSUE THREAD

**Issue by genysta** [EvilFreelancer/routeros-api-php#57]
How can i run "system script run Test" ?
i've tried where('name', 'Test') but it return script not found
i've tried equal('name', 'Test') but it give me unknown parameter

Is there any option to do that?

**Comment by EvilFreelancer** [comment]
Hello! You need to try following solution.

Get list of all available scripts, from this list you need ID of required scripts (filter by name, then extract ID)
```php
$query = new Query('/system/script/print');
$scripts = $client->query($query)->read();

$id = null;
forerch ($scripts as $script) {
  if ($script['name'] === 'Test') {
    $id = $script['id'];
    break 1;
  }
}
```
For example your ID will looks like `*1e`.

Then need call `run` and pass this ID via `equal` method:
```php
$query = (new Query('/system/script/print'))->equal('.id', '*1e');
$run = $client->query($query)->read();
```

**Comment by genysta** [comment]
I use
`->equal('.id', 'Test')`
And it works for me.

Thank you so much
