### ISSUE TITLE
Query /ip/firewall/nat/print won't return all results

### ISSUE THREAD

**Issue by LukMRVC** [EvilFreelancer/routeros-api-php#6]
Using with with legacy firmware, when executing query /ip/firewall/nat/print I get back only a part of what's actually on the device. 
When I tried using a different library I got back all of results. 
Tried resolving this issue by myself but I failed.

**Comment by EvilFreelancer** [comment]
Hello! Thank you for issue, I'll check this bug soon.

**Comment by matracine** [comment]
Hello,
I tested with 200 nat rules without problem.
Did you upgrade the lib to v0.8.2 ? It's probably the same problem than with #2.

**Comment by LukMRVC** [comment]
Hi,
so yeah, the problem was on my side as I didn't had new version of the library.
Upgraded to new version and everything is running fine now,
Thanks for your help.
