### ISSUE TITLE
Unable to update simple queue

### ISSUE THREAD

**Issue by mercrover** [EvilFreelancer/routeros-api-php#61]
Thank you @EvilFreelancer for this wonderful package. Am testing your package but I cannot update a simple queue max-limit or any other parameter. Here's my code:

```
$query = new \RouterOS\Query('/queue/simple/set');
	$query->equal('name', "TestQueue");
	$query->equal('max-limit', "10000/10000");

$response = $client->query($query)->read(); // dd($response); gives !done

$response = $client->query('/queue/simple/print', ['name', 'TestQueue'])->read(); 
dd($response); // no change to the queue
```

What's the issue?

**Comment by EvilFreelancer** [comment]
Hello! Hmmm, seems you forgot to pass ID of item in simple queue, try get list of rules via `/queue/simple/print` then use `*id` field as third "equal" of your `/queue/simple/set` call.

**Comment by mercrover** [comment]
Awesome! Yep, it worked! Thanks, this has taken me many days to figure out!
