### ISSUE TITLE
Cant change ppp secrets information

### ISSUE THREAD

**Issue by muhammad-ihsan** [EvilFreelancer/routeros-api-php#62]
hi there, did i miss something here? because I cant change the value of secrets profile (disabled status). Here is my code:
```
$config =
    (new Config())
        ->set('host', env('MIKROTIK_IP'))
        ->set('user', env('MIKROTIK_USERNAME'))
        ->set('pass', env('MIKROTIK_PASSWORD'));

// Initiate client with config object
$client = new Client($config);

// Get list of all available profiles with name Block
$query = new Query('/ppp/secret/set');
$query->where('name', 'HOUSE');
$query->equal('disabled', 'yes');
$secrets = $client->query($query)->read();
return $secrets;
```

**Comment by EvilFreelancer** [comment]
Hello! For update/create/delete API calls need to use only 'equal()' method, try to replace to it from 'where()' and recheck again :)

**Comment by muhammad-ihsan** [comment]
Well okay already tested. Bu set data is not working with `equal('name')` by name, but works with `equal('.id')`

**Comment by EvilFreelancer** [comment]
Some endpoints can work with data without ID, but some other need to pass ID. You may check it via CLI.
