### ISSUE TITLE
Error reading 1 bytes

### ISSUE THREAD

**Issue by wartw** [EvilFreelancer/routeros-api-php#68]
This error often occurs when there are more than tens of thousands of concurrent requests

Fatal error: Uncaught RouterOS\Exceptions\StreamException: Error reading 1 bytes in /www/wwwroot/e5218129d40e2b46.sn.mynetname.net/routeros-api-php/src/Streams/ResourceStream.php:59 Stack trace: #0 /www/wwwroot/e5218129d40e2b46.sn.mynetname.net/routeros-api-php/src/APILengthCoDec.php(115): RouterOS\Streams\ResourceStream->read() #1 /www/wwwroot/e5218129d40e2b46.sn.mynetname.net/routeros-api-php/src/APIConnector.php(53): RouterOS\APILengthCoDec::decodeLength() #2 /www/wwwroot/e5218129d40e2b46.sn.mynetname.net/routeros-api-php/src/Client.php(255): RouterOS\APIConnector->readWord() #3 /www/wwwroot/e5218129d40e2b46.sn.mynetname.net/routeros-api-php/src/Client.php(310): RouterOS\Client->readRAW() #4 /www/wwwroot/e5218129d40e2b46.sn.mynetname.net/routeros-api-php/src/Client.php(481): RouterOS\Client->read() #5 /www/wwwroot/e5218129d40e2b46.sn.mynetname.net/routeros-api-php/src/Client.php(538): RouterOS\Client->login() #6 /www/wwwroot/e5218129d40e2b46.sn.mynetname.net/routeros-api-php/src/Client.php(88): RouterOS\Client->connect in /www/wwwroot/e5218129d40e2b46.sn.mynetname.net/routeros-api-php/src/Streams/ResourceStream.php on line 59

**Comment by EvilFreelancer** [comment]
Hey! I'm not sure if this is a problem with this library, the RouterOS API is a very fragile thing in itself.

My opinion is that you see this error because the size of the buffer allocated for processing API requests was exceeded, I am sure that if you try to repeat this procedure using any other library, you will get a similar error.

Check the RouterOS logs first, probably answer will be here at the moment when this error occurs.

**Comment by matracine** [comment]
Hello,
This error is triggered when the underlying lib did not manage to read data from the router.
I think that, as Paul said, your router is overloaded and cannot answer correctly to the API call.
@EvilFreelancer Perhaps it could be interesting to catch the StreamException at a higher level and rethrow a more contextualy explicit one ?

**Comment by EvilFreelancer** [comment]
Hello @matracine it's a good idea! I guess for the first need to reproduce this error via tests and add exception. You did the part about working with streams, perhaps it would be better if you implement this exception :)

**Comment by EvilFreelancer** [comment]
You probably mean source ip?

Nope, library doe not support this.

**Comment by wartw** [comment]
I mean, for example, if there are 192.168.1.2~5 in the vm, can you specify one of them to access ros?

**Comment by EvilFreelancer** [comment]
The RouterOS API is not an ordinary HTTP API (RESTful/SOAP/GraphQL/etc.), it's TCP-based, with a non-typical format of requests and responses, with bitwise shifting. Communication between the API server takes place using the stream extensions, options can be passed via [stream_context_create](https://github.com/EvilFreelancer/routeros-api-php/blob/master/src/SocketTrait.php#L43) method. And as i know in raw TCP mode not possible to use proxy.

**Comment by EvilFreelancer** [comment]
@matracine thanks, I did not know about this solution. Need to add this useful option to one future releases.

**Comment by EvilFreelancer** [comment]
Hello! I've added support of `socket_options` parameter to the Config object.

https://github.com/EvilFreelancer/routeros-api-php#list-of-available-configuration-parameters
https://github.com/EvilFreelancer/routeros-api-php/blob/master/src/Config.php#L87

It's easy to use:
```php
$client = new Client([
    'socket_options' => [
        'bindto' => '192.168.1.10:7000'
    ]
]);
```

Already available in version 1.4.5.

**Comment by wartw** [comment]
I forgot to tell you, it works

**Comment by wartw** [comment]
Very good operation (processing tens of thousands of different records at the same time, there will be no abnormalities
