### ISSUE TITLE
try catch

### ISSUE THREAD

**Issue by Tahernejad** [EvilFreelancer/routeros-api-php#69]
Hello,
How can detect connection or login is successful or not ?
Please help me with example, 
Thanks a lot.

**Comment by EvilFreelancer** [comment]
Hello! Interesting question, it should be already implemented in exceptions.

This `stream_set_blocking(): Argument #1 ($stream) must be of type resource, bool given` there is no stream instantiated.

I'll check why exception was not triggered before.

**Comment by EvilFreelancer** [comment]
Hello! Try to use this https://www.php.net/manual/ru/exception.getmessage.php

**Comment by EvilFreelancer** [comment]
Hello! I've added additional check for stream resource, available in 1.4.3
https://github.com/EvilFreelancer/routeros-api-php/blob/master/src/SocketTrait.php#L57

**Comment by Tahernejad** [comment]
Thank you very much ❤
