### ISSUE TITLE
where clause

### ISSUE THREAD

**Issue by medeirosinacio** [EvilFreelancer/routeros-api-php#7]
Hello, I tried in many ways but I can not create a query using where, does your class support this?

Ex:

`$query    = new Query('/queue/simple/print/where', ['name=123123']);
or
$query    = new Query('/queue/simple/print', ['where', 'name=123123']); `

**Comment by EvilFreelancer** [comment]
Hello @medeirosinacio ! Yep, it should work, but API has some small difference with CLI of RouterOS, for details you need look at [this manual](https://wiki.mikrotik.com/wiki/Manual:API#Queries). You also can look at [this example](https://github.com/EvilFreelancer/routeros-api-php/blob/master/examples/queue_simple_print_v2.php), sample of code:
```php
foreach ($ips as $ip) {
    $response = $client->wr([
        '/queue/simple/print',
        '?target=' . $ip . '/32'
    ]);
    print_r($response);
}
```
As you can see analog of "where" is "?", I hope it help for you!

**Comment by medeirosinacio** [comment]
Perfect, you save my life :D
