### ISSUE TITLE
Browser refreshes endlessly after /interface/monitor-traffic

### ISSUE THREAD

**Issue by ArtMin96** [EvilFreelancer/routeros-api-php#70]
After requesting this api, the browser refreshes endlessly and I have to restart the server.

```php
$query = (new Query('/interface/monitor-traffic'))
            ->where('interface',  'ether2')
            ->where('once');

$response = $this->client->query($query)->read();
```

**Comment by EvilFreelancer** [comment]
Hello! This command read all traffic from interface and shows you information about packages with dynamic refreshing of command line.
```
[admin@MikroTik] > /interface monitor-traffic ether1 
                         name:     ether1
        rx-packets-per-second:         24
           rx-bits-per-second:  171.0kbps
     fp-rx-packets-per-second:         22
        fp-rx-bits-per-second:  143.9kbps
          rx-drops-per-second:          0
         rx-errors-per-second:          0
        tx-packets-per-second:         18
           tx-bits-per-second:   16.0kbps
     fp-tx-packets-per-second:         18
        fp-tx-bits-per-second:   15.5kbps
          tx-drops-per-second:          0
    tx-queue-drops-per-second:          0
         tx-errors-per-second:          0
-- [Q quit|D dump|C-z pause]
````

Same will be via API, but this library detects end of response from API, ordinary it's a '!done' and zero line after that, but in traffic-monitor mode there is no !done+zero, and library don't know what to do.

So, you see infinity loading is a consequence imperfection of the library.

At the moment, I do not know how to implement the processing of a infinity stream of data, this library was conceived for other tasks, and these tasks have a start point and a termination point, so it is easy to process the response.

But thanks for noticing this issue, I will try to solve it somehow.

**Comment by EvilFreelancer** [comment]
Yep, I know about library you mentioned :)

Here is a small quote from README of current project:

https://github.com/EvilFreelancer/routeros-api-php#routeros-api-client

> This library is partly based on [this old project](https://github.com/BenMenking/routeros-api), but unlike it has many
> innovations to ease development. In addition, the project designed
> to work with PHP7/8 in accordance with the PSR standards.

And as I know sulution by @BenMenking's library is also does not support infinity loading.

**Comment by ArtMin96** [comment]
Thanks again
