### ISSUE TITLE
find where

### ISSUE THREAD

**Issue by Tahernejad** [EvilFreelancer/routeros-api-php#74]
Hello

`
$query = (new Query('/radius/find'))
	->where('address', '192.168.100.100');
$rad= $client->query($query)->read();
$rad=$rad["after"]["ret"];
$rad=str_replace(';', ',', $rad);
$query = (new Query('/radius/remove'))
	->equal('numbers',$rad);
$ret = $client->query($query)->read();
`

'where' not working and removed all radius

**Comment by EvilFreelancer** [comment]
Hello! Thanks for you report, i'll check it.

**Comment by diegotibi** [comment]
Hi @Tahernejad 
take a look here: #87

**Comment by Tahernejad** [comment]
Thanks @diegotibi 
Yes, I solved by using "print" instead of "find".
