### ISSUE TITLE
RouterOS 7.1

### ISSUE THREAD

**Issue by imilos** [EvilFreelancer/routeros-api-php#75]
Does it work with the new RouterOS 7.1?

**Comment by EvilFreelancer** [comment]
Hello! I've tested the library on RouterOS 7.0-beta and everything was okay, so I guess on 7.1 also everything will be okay :)

**Comment by EvilFreelancer** [comment]
If, nevertheless, something does not work, just describe your issue here, for debug I need an error message, sample of code and PHP version.

**Comment by imilos** [comment]
Thanks for your reply. I'll give it a try.

**Comment by n4yeem** [comment]
> Thanks for your reply. I'll give it a try.

Hey 

did you checked it with ROS v7? is it working properly?

**Comment by EvilFreelancer** [comment]
Hi! Yep, seems everything works same as on 6.4x.x (i mean okay).
If i understand correctly only a Web-UI was changed in this new release, but API works same as before.
