### ISSUE TITLE
How to remove active pppoe user?

### ISSUE THREAD

**Issue by n4yeem** [EvilFreelancer/routeros-api-php#76]
Hi
I try to disconnect active pppoe user from mikrotk. but i receive an error saying no such command. In mikrotik i disconnect user by typing to interface pppoe-server remove <pppoe-username>. I tried to disconnect user by using this command to disconnect pppoe user  interface/pppoe-server/remove /<pppoe-username>

Can someone guide me what am i doing wrong?

**Comment by EvilFreelancer** [comment]
Hello! Which API call you used for interacting with router? Code sample?

**Comment by n4yeem** [comment]
> Hello! Which API call you used for interacting with router? Code sample?

    public function disconnectConnectedUser()
    {
        $query_ppp_deactive_user = new Query("/interface/pppoe-server/print", ['name', 'pppoe-user01']);
        $user =  $this->client->query($query_ppp_deactive_user)->read();
        $data =   $user[0]['.id'];
        $deactive_user = new Query("/interface/pppoe-server/remove/numbers=$data");
        return $this->client->query($deactive_user)->read();
    }
![photo_2022-01-21_15-43-20](https://user-images.githubusercontent.com/52958735/150504426-a725c050-2d5b-431d-8d66-238b0d3e37ea.jpg)

**Comment by n4yeem** [comment]
I also tried to remove user  /ppp/active/remove/numbers=
it shows same error "no such command"

**Comment by matracine** [comment]
Hello,
I think, it should be : 
``php
return (new Query('interface/pppoe-server/remove'))->where('.id', user[0]['.id'])->read();
``

**Comment by EvilFreelancer** [comment]
Hello! Seems you need to removed item from RouterOS, for this need to use `equal` method of Query object.

```php
public function disconnectConnectedUser()
{
    $query_ppp_deactive_user = new Query("/interface/pppoe-server/print", ['name', 'pppoe-user01']);
    $user =  $this->client->query($query_ppp_deactive_user)->read();
    $data =   $user[0]['.id'];
    $deactive_user = new Query("/interface/pppoe-server/remove")->equal('numbers', $data);
    return $this->client->query($deactive_user)->read();
}
```

Try this and ping if everything is okay :)

**Comment by n4yeem** [comment]
> Hello! Seems you need to removed item from RouterOS, for this need to use `equal` method of Query object.
> 
> ```
> public function disconnectConnectedUser()
> {
>     $query_ppp_deactive_user = new Query("/interface/pppoe-server/print")->where('name', 'pppoe-user01');
>     $user =  $this->client->query($query_ppp_deactive_user)->read();
>     $data =   $user[0]['.id'];
>     $deactive_user = new Query("/interface/pppoe-server/remove")->equal('numbers', $data);
>     return $this->client->query($deactive_user)->read();
> }
> ```
> 
> Try this and ping if everything is okay :)

sure.. i will let you know the updates. thanks for ur reply.

**Comment by n4yeem** [comment]
> Hello! Seems you need to removed item from RouterOS, for this need to use `equal` method of Query object.
> 
> ```
> public function disconnectConnectedUser()
> {
>     $query_ppp_deactive_user = new Query("/interface/pppoe-server/print")->where('name', 'pppoe-user01');
>     $user =  $this->client->query($query_ppp_deactive_user)->read();
>     $data =   $user[0]['.id'];
>     $deactive_user = new Query("/interface/pppoe-server/remove")->equal('numbers', $data);
>     return $this->client->query($deactive_user)->read();
> }
> ```
> 
> Try this and ping if everything is okay :)

This is the correct code that is working.

$query_ppp_deactive_user = (new Query("/interface/pppoe-server/print"))->where('name', '<pppoe-user01>');
        $user = $this->client->query($query_ppp_deactive_user)->read();
        $rmUser = (new Query('/interface/pppoe-server/remove'))->equal('numbers', $user[0]['.id']);
        return $this->client->query($rmUser)->read();

**Comment by n4yeem** [comment]
For Some reason github is not showing the full query . I have attached the pic for better understanding. 
![image](https://user-images.githubusercontent.com/52958735/150647409-5fe8f9d3-2431-4ecd-841c-b187f8812e37.png)

**Comment by EvilFreelancer** [comment]
Yep, sorry for typo, I've sent a message from phone.

So everything is okay now and issue may be closed, right?

**Comment by n4yeem** [comment]
> Yep, sorry for typo, I've sent a message from phone.
> 
> So everything is okay now and issue may be closed, right?

Yes.. I am closing this issue. Thanks for your prompt reply.
