### ISSUE TITLE
API, Available from

### ISSUE THREAD

**Issue by Tahernejad** [EvilFreelancer/routeros-api-php#77]
Hello,
I try on many devices with different version.
If ip address trying to connet api is not listed on api available ip address list, no any error and action with script, it waiting and waiting.

Some times return "Error reading 1 bytes"

**Comment by szastan** [comment]
Hi, this is expected behavior as client has to wait until timeout occurs. Until you receive packets with response you don’t really know what is happening. 

Kamil

**Comment by jonth93** [comment]
As @szastan stated, this is expected behaviour and not a bug.
If the API connection is coming from an IP address not listed in the address parameter on `/ip/services api` the router will silently drop the packets and your API connection will not receive a response.
