### ISSUE TITLE
getting detailed information for interface

### ISSUE THREAD

**Issue by danmadar** [EvilFreelancer/routeros-api-php#78]
Hello, 
i'm trying to get an interface print detail using the API. Using the terminal command looks something like this : 
/interface ethernet print detail 
This command prints more detailed information about the ports.
Thank You in advance

**Comment by jonth93** [comment]
I'm working with version 1.2, but this query should still work.

`$intDetails = (new Query('/interface/ethernet/print))->add('=detail=')`

**Comment by EvilFreelancer** [comment]
Analogue in a new version is:
```
$intDetails = (new Query('/interface/ethernet/print))->equal('detail')
```
