### ISSUE TITLE
PPPoE remote address unset-edit-remove

### ISSUE THREAD

**Issue by n4yeem** [EvilFreelancer/routeros-api-php#81]
i want to change remote address of an user.but the is  command doesnt work., I want to remove remote-address key from object. 
how can i do this?
This is what i am using

 public function chnageUserProfile($username)
    {
        $system_profile = Softwaresystem::select('disconnected_package')->first();
        $query_ppp_pool = (new Query("/ppp/secret/print"))->where('name', $username);
        $secrets  =  $this->client->query($query_ppp_pool)->read();
        foreach ($secrets as $secret) {
            $query = (new Query('/ppp/secret/set'))
                ->equal('.id', $secret['.id'])
                ->equal('profile', $system_profile['disconnected_package'])
                ->equal('remote-address', ' ');
             $this->client->query($query)->read();
        }
        $query_ppp_pool = (new Query("/ppp/secret/print"))->where('name', $username);
        return $this->client->query($query_ppp_pool)->read();
    }

**Comment by EvilFreelancer** [comment]
Hello! Interesting question, probably the reason in a multiple equals, did you tried to change profile and remote-address via two different requests?

**Comment by n4yeem** [comment]
I havent checked it yet. let me check it and see the result! maybe it will work if i made two different request!

**Comment by jonth93** [comment]
In your `->equal('remote-address', ' ');` you've got a space between the apostrophes, I'm sure this needs to be `''` no space.

I've got this to remove all DNS servers from `ip/dns` / `$dnsSettings->equal('servers' . '');` and I get the desired result.
