### ISSUE TITLE
Unable to use /ping will not output the content

### ISSUE THREAD

**Issue by wartw** [EvilFreelancer/routeros-api-php#82]
Unable to use /ping
will not output the content

**Comment by jonth93** [comment]
In RouterOS ping tool is never ending (as it's Linux based), which would expect this API to read the continuous output, but the router will never issue `!done` whilst the command is running. So you'll never get the output.

You'll want to add **count** to the end of the command to get an output and close off the connection.

See [https://github.com/EvilFreelancer/routeros-api-php/blob/master/examples/monitoring.php](url) for an example of monitoring traffic on an interface by adding `once` to the query.

**Comment by EvilFreelancer** [comment]
Yep, need to limit it via count of packets.
