### ISSUE TITLE
Error Stream timed out

### ISSUE THREAD

**Issue by fikurimax** [EvilFreelancer/routeros-api-php#85]
I tried to read user profiles but keep getting this error 

`Stream timed out {"exception":"[object] (RouterOS\\Exceptions\\StreamException(code: 0): Stream timed out at C:\\laragon\\www\\projectname\\vendor\\evilfreelancer\routeros-api-php\\src\\Streams\\ResourceStream.php:55)`

but somehow when I create a user it just works fine

code I used:
```
try {
        $client = new Client(new Config([
            'host'  => $address,
            'user'  => $user,
            'pass'  => $pass,
            'port'  => (int) $port
        ]));
    } catch (\Throwable $th) {
        throw $th;
    }

$profiles = $client->query(new Query('/ip/hotspot/user/profile/print'))->read();
```

**Comment by fikurimax** [comment]
I just tested by creating a new user profile and it succeed, only print command doesn't work

**Comment by EvilFreelancer** [comment]
Hi! Which version of RouterOS do you have?

Did you tried to increase a stream timeout option?

https://github.com/EvilFreelancer/routeros-api-php/blob/master/src/Config.php#L134-L135

**Comment by fikurimax** [comment]
I just solved it. apparently, the port collides with other services. Thanks for responding
