### ISSUE TITLE
Find command doesn't support query

### ISSUE THREAD

**Issue by diegotibi** [EvilFreelancer/routeros-api-php#87]
**Version of RouterOS**
Any, or at least any recent.

**To Reproduce**
Create a couple of lists on a mikrotik device with some ips:

```
/ip firewall address-list
add address=192.168.1.1 list=list1
add address=192.168.1.2 list=list1
add address=10.10.0.1 list=list2
add address=10.10.0.2 list=list2
```

Then execute this code:

```php
$query = (new Query('/ip/firewall/address-list/find'))
    ->where('list', 'list1');

$ips = $client->qr($query);
$ips = $ips["after"]["ret"];

var_dump($ips);
```

**Expected behavior**
In theory you should receive a list of two ip addresses, instead you'll receive back the list of all addresses because the query is simply ignored.

**Possible solution**
You can try something like this:

```php
$query = (new Query('/ip/firewall/address-list/print'))
    ->equal('.proplist', '.id')
    ->where('list', 'list1');

$ips = [];
foreach ($client->qr($query) as $item) {
    $ips[] = $item['.id'];
}
$ips = implode(";", $ips);

var_dump($list);
```

**Reference**
[Mikrotik Wiki](https://wiki.mikrotik.com/wiki/Manual:API#Query_word)

If you read carefully there's a line saying:
_Currently only print command handles query words._

So said, the *wipe_address_list.php* example is misleading since you'll wipe all addresses and not only the ones you actually want to remove!

**Comment by EvilFreelancer** [comment]
Hi! You can't mix `equal` and `where` methods at the same time, it's a "feature" of Mirotik API, for `/find` you need pass all options via `equal` method only.
