### ISSUE TITLE
script stucks when devbice is unavaiable

### ISSUE THREAD

**Issue by KR2615** [EvilFreelancer/routeros-api-php#88]
Hi. I noticed, that PHP script based on EvilFreelancer/routeros-api-php stucks when PHP machine is not allowed to use API (IP Services > Available from) The port on the device is open, IP pinging but the PHP script is executing for infinity. There's no exception thrown (I'm catching it) How can I help you to fix the issue?

**Comment by darthsta** [comment]
I'm also having this issue when connecting to a device where the ssh service isn't working.  instead of an error being thrown the script just hangs.

**Comment by EvilFreelancer** [comment]
Hello! Thanks for report, i've reproduced an issue
