### ISSUE TITLE
requires ext-sockets

### ISSUE THREAD

**Issue by fuadi4161** [EvilFreelancer/routeros-api-php#89]
Package evilfreelancer/routeros-api-php has requirements incompatible with your PHP version, PHP extensions and Com
  poser version:
    - evilfreelancer/routeros-api-php 1.4.3 requires ext-sockets * but it is not present.

**Comment by EvilFreelancer** [comment]
Hello! This is not a package, it's a php extension, without this extension not possible to communicate with RouterOS API.

So you just need to instal it via packages manager to your host. Name of package will looks like php-sockets or something like that.
