### ISSUE TITLE
Access via non Real IP builtin VPN Access

### ISSUE THREAD

**Issue by fhmunna** [EvilFreelancer/routeros-api-php#9]
Can we achieve this API access via mikrotik provided vpn ID e.g. 999999d229c.sn.mynetname.net

Please provide sample of such communication which is necessary for routers without any real IP..

Thanks in advance.

**Comment by EvilFreelancer** [comment]
@fhmunna hello! Your question does not quite relate to this PHP library or RouterOS, is more about your local network settings and tunneling, for example you can try to use stunnel via ssh:
![stunnel](http://1.bp.blogspot.com/-ZgZzxrj5xeA/UnpVNboJ80I/AAAAAAAACCY/WSk00meAhrg/w1200-h630-p-k-no-nu/ssh-tunneling.png)

In any case if you has no access to your router from internet and your PC is also don't accessable directly from internet, you need to use some "transshipment point" - server with static IP which available from both host (router and PC).

Or just set static IP on your router (you need ask your ISP about this) and configure any VPN server, IPSec for example, then connect from PC and work with router's API directly.
