### ISSUE TITLE
Multiple query

### ISSUE THREAD

**Issue by mitch0er** [EvilFreelancer/routeros-api-php#90]
Did multiple queries possible? My goal is to get average latency for a 10-second ping and at the same time, average traffic in those 10 seconds from my interface with monitor-traffic
I have tried 
`$client->query($ping)->query($traffic)->read();`
But what it's returned is just $traffic query

**Comment by EvilFreelancer** [comment]
Hello! It is possible, just try something like this:
```php
$client->query($ping)->read();
$client->query($traffic)->read();
```

**Comment by mitch0er** [comment]
Are those 2 running at the same time? or the traffic query executed after ping query?

**Comment by EvilFreelancer** [comment]
PHP is synchronous language, if you need some async functional then use something like parallel, pthreads, or pcntl.

But by default traffic query will be executed after ping query.

**Comment by mitch0er** [comment]
Thanks for the answer
