### ISSUE TITLE
Upgrade phpseclib

### ISSUE THREAD

**Issue by malikdoksoz** [EvilFreelancer/routeros-api-php#91]
**Version of RouterOS**
1.4.3

divineomega/php-ssh-connection v2.2.0 requires phpseclib/phpseclib ^2.0 -> found phpseclib/phpseclib[2.0.0, ..., 2.0.x-dev] but it conflicts with your root composer.json require (^3.0).
evilfreelancer/routeros-api-php 1.4.3 requires divineomega/php-ssh-connection ^2.2 -> satisfiable by divineomega/php-ssh-connection[v2.2.0].

divineomega/php-ssh-connection package used phpseclib v2,  needs to be upgraded to v3

**Comment by EvilFreelancer** [comment]
Hi! Hm, interesting, seems author of php-ssh-connection abandoned project:
https://github.com/DivineOmega/php-ssh-connection

I'll check, thanks for report!

**Comment by malikdoksoz** [comment]
> Hi! Hm, interesting, seems author of php-ssh-connection abandoned project: https://github.com/DivineOmega/php-ssh-connection
> 
> I'll check, thanks for report!

Exactly. You can replace it with this repo: https://github.com/spatie/ssh

**Comment by EvilFreelancer** [comment]
Thanks for advice, i'll check this library today, after work.

**Comment by malikdoksoz** [comment]
You r welcome, thank you for your quick response.

**Comment by rdemendoza** [comment]
Hello,
any update on this issue ?

**Comment by EvilFreelancer** [comment]
Hello! Oops, seems i've forgot to upload fix :)

**Comment by EvilFreelancer** [comment]
Try release 1.5.0
