### ISSUE TITLE
Why is it that when I try to use local it's fine, whereas when I try to upload it on the cpanel liveserver it can't connect

### ISSUE THREAD

**Issue by hanafiabdilah** [EvilFreelancer/routeros-api-php#92]
$client = new Client([
      'host' => 'id-10.hostddns.us:1234', // remote vpn
      'user' => 'admin',
      'pass' =>  'admin'
  ]);

**Comment by EvilFreelancer** [comment]
Hello! Look at #56

**Comment by hanafiabdilah** [comment]
After I studied deeper. 
Is it possible because I keep it on shared hosting? do i have to store on vps server?

**Comment by EvilFreelancer** [comment]
Hi! Or you may update firewall rules and allow access to router from the library side. But i guess you already solved this :)
