### ISSUE TITLE
remove pppoe active not work

### ISSUE THREAD

**Issue by beryindo** [EvilFreelancer/routeros-api-php#95]
Laravel 10 remove pppoe active not work, but print work.
```
$query = new Query('/ppp/active/remove');
$query->where('.id', '*800002A3');
$response = $client->query($query)->read();
```

**Comment by EvilFreelancer** [comment]
Hello! Use equal instead of where, more details in readme.

https://github.com/EvilFreelancer/routeros-api-php/tree/master#how-to-write-queries
