### ISSUE TITLE
works with angular or nextjs frontend?

### ISSUE THREAD

**Issue by agaitan026** [EvilFreelancer/routeros-api-php#98]
Hello, one question, this works with angular or nextjs frontend?

thank you

**Comment by EvilFreelancer** [comment]
Hello!

Absolutely! You can use this PHP library in conjunction with an Angular or Next.js frontend but... not directly. These JavaScript frameworks run on the client side (in the user's browser) (in case you don't use Next.js in SSR mode), while PHP runs on the server side.

So, the communication between your frontend (Angular/Next.js) and backend (PHP) would typically be done through HTTP requests (like REST or GraphQL API calls) or other similar methods. Your PHP backend would process the requests and send back responses, which your frontend would then interpret and display.

Make sure your PHP backend exposes the necessary functionality of the PHP library you want to use as API endpoints, and then your Angular or Next.js frontend can make requests to these endpoints to use that functionality.

If you are interested in a JavaScript client for MikroTik API, you may want to check out this topic on GitHub [here](https://github.com/topics/mikrotik-api?l=javascript) or check [MikroNode](https://github.com/Trakkasure/mikronode) project.

I hope this helps! Let me know if you have any other questions.
